### PR TITLE
add django based migrations for django >= 1.7

### PR DESCRIPTION
**Pull request by dersphere**
Like discussed in #3, this adds blank django migrations (as non default).

I suggest adding a phrase like this to the readme as other django_cms apps are doing the same:
```
If using Django >= 1.7 add 'image_gallery': 'image_gallery.migrations_django' to MIGRATION_MODULES (or define MIGRATION_MODULES if it does not exists).
```
This fixes ```"django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'image_gallery.GalleryPlugin'>]"``` Exception.

### CODE REVIEW

**Comment by dersphere** [comment]
Also, have a look to: https://github.com/tsbarnes/cmsplugin-image-gallery/commit/02d3dc52915429dfbc8042fe69a6b35bb5c0e47d

@tsbarnes seems to have a more complete approach!
(Damn that I didn't see this earlier)

**Comment by Tyrdall** [comment]
Mhm, I won't worry. He only updated the requirements and added the ``MIGRATION_MODULES`` settings. Personally I would rename the ``migrations`` folder to ``south_migrations`` and call the new migrations folder ``migrations``. I will then add a hint to the README that devs using Django<=1.6 will have to use the following setting:

    SOUTH_MIGRATION_MODULES = {
        'image_gallery': 'image_gallery.south_migrations',
    }

I know it's only the other way around, but doing it that way we can get rid of the setting in future versions. Thanks!

You might also want to add an exception to the ``__init__.py`` of the new migration folder.

    """
    Migrations used by Django 1.7.
    South migrations can be found in the ``south_migrations`` package.
    """

    SOUTH_ERROR_MESSAGE = """\n
    If you're on Django 1.6 (or earlier), you'll need to set SOUTH_MIGRATION_MODULES.
    Please refer to the installation docs.
    """

    # Ensure the user is not using Django 1.6 or below with South
    try:
        from django.db import migrations
    except ImportError:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(SOUTH_ERROR_MESSAGE)

Stolen from http://treyhunner.com/2014/03/migrating-to-django-1-dot-7/ ;)

**Comment by dersphere** [comment]
Sure, using the new system as default makes sense. I didn't do that because it would break the app for you in your own project ;)
You choose (Also feel free to just close my PR and do it like you want/need) :)

**Comment by Tyrdall** [comment]
Hehe, don't want to bother =) Please do me a favour and add the changes for the new system to your request. I will merge it directly. Thanks a lot.

Please let me know when you want me to push a new version to PyPi.

**Comment by dersphere** [comment]
Done (by force pushing).
The readme needs some love now.
My requirements are most-recent versions so I can confirm them working together:
````
django-cms==3.1.0
django-filer==0.9.10
Django==1.7.8
````
Sure, pypi update would simplify my requirements.txt :)

**Comment by Tyrdall** [comment]
@dersphere Thanks a lot for your contribution!

https://pypi.python.org/pypi/cmsplugin-image-gallery/0.7.0

**Pull request merged**
